### ISSUE TITLE
Shared element reverse transition does not work after screen rotation

### ISSUE THREAD

**Issue by mhBahrami** [android/plaid#131]
Hi,
Hope all is well. In the home screen, there is a fab button to add account. After clicking, there is a transition between this fab button and the new item to log in. If the user wants can close it by Back Button. In that time reverse transition will work fine. 
**Steps:**
1. Click on FAB button (in home screen)
2. Transition works
3. Click on back button
4. Reverse transition works

**Problem**: If you follow below steps Reverse transition does not work
**Steps:**
1. Click on FAB button (in home screen)
2. Transition works
3. _**Rotate device to rotate screen**_
4. Click on back button
5. Reverse transition _**does not work**_

**Comment by pfmaggi** [comment]
Obsolete
