### ISSUE TITLE
FabTransform elevation shadows bug 

### ISSUE THREAD

**Issue by codeversed** [android/plaid#139]
More or less I am creating this to just say FYI and for tracking purposes.

I am pretty sure that this bug is recently reported here: https://code.google.com/p/android/issues/detail?id=191267

**In short: "We have an internal bug on this, but it is going to take a while before we get to it."**

Currently, your workaround is the best result that I have gotten (tried a bunch of hacky things). It seems sometimes depending on my layouts and mix of views, it works as it should. Maybe just the animations slowing down fractions of a second from the amount of visible view... no idea.

It's so minor but my OCD will be the death of me!

**Comment by keyboardsurfer** [comment]
There's no more FAB in Plaid, but I'm following up on the AOSP bug. Thanks.
