### ISSUE TITLE
Item can be opened twice

### ISSUE THREAD

**Issue by sergeyfitis** [android/plaid#147]
Double click on one item opens it twice
[video](https://dl2.pushbulletusercontent.com/RlmtcHTqGsVSMN0UE8oD7DlnMC3nZ00Q/plaid_bug.mp4)

**Comment by shobhitagarwal1612** [comment]
Hello! I would like to tackle this bug. Should I go ahead?

**Comment by nickbutcher** [comment]
@shobhitagarwal1612  sure, go for it. We should likely use `ButterKnife` more liberally for click handlers which prevents this issue.
