### ISSUE TITLE
Likes counter is not completely visible in Nexus 9

### ISSUE THREAD

**Issue by Sottti** [android/plaid#153]
**Description:**
The counter on a comment is partially visible.

**Unexpected behaviour and possible issue: (Nexus 9)**
<img src="https://cloud.githubusercontent.com/assets/4732495/21293272/40cf65a2-c517-11e6-9e6e-4311cb208121.png" width="50%">

**Expected behaviour: (Google Pixel XL)**
<img src="https://cloud.githubusercontent.com/assets/4732495/21293271/40ce8236-c517-11e6-8df8-4086f9c677bb.png" width="50%">

**Comment by keyboardsurfer** [comment]
This is most likely obsolete. Please re-open if the issue persists.
