### ISSUE TITLE
Multiple loading icons visible

### ISSUE THREAD

**Issue by chintandesai49** [android/plaid#156]
After loading some items and turning off the internet following loading icons are showed up.
Device: Nexus 4
Steps: Load few data in the list-> Afetr loading few data turn off the internet connection
![screenshot_2016-12-30-14-10-12_ink_li](https://cloud.githubusercontent.com/assets/13096315/21593321/d191f6d8-d13b-11e6-96ce-6a3a02d0a89e.jpg)

**Comment by keyboardsurfer** [comment]
Could not verify with current master. Please re-open if the issue persists.
