### ISSUE TITLE
Do not show item if adapter size is equal to 1

### ISSUE THREAD

**Issue by oNguyenHuuTho** [android/plaid#212]
-if the Adapter has size = 1, the item is not displayed
-from 2 items or more, the display is normal
  Hope you reconsider and fix it
Sorry for my bad english

**Comment by prudhviraj038** [comment]
You can set another layout manager if adapter size is , this block of code may help you

if (brands.models.size()<=1) {
            recyclerView.setLayoutManager(new LinearLayoutManager(this));
        }else {
            recyclerView.setLayoutManager(new SpannedGridLayoutManager(
                    new SpannedGridLayoutManager.GridSpanLookup() {
                        @Override
                        public SpannedGridLayoutManager.SpanInfo getSpanInfo(int position) {
                            if (position == 0) {
                                return new SpannedGridLayoutManager.SpanInfo(2, 1);
                            } else {
                                return new SpannedGridLayoutManager.SpanInfo(1, 1);
                            }
                        }
                    },
                    2/* Three columns */,
                    1f /* We want our items to be 1:1 ratio */));
        }

**Comment by keyboardsurfer** [comment]
Could not verify with the current state of master.

**Comment by AlbertZyc** [comment]
In fact, I have encountered this problem too, when the data size is 1, the display will be abnormal
/***The following code does work***/
if (brands.models.size()<=1) {
recyclerView.setLayoutManager(new LinearLayoutManager(this));
}else {
recyclerView.setLayoutManager(new SpannedGridLayoutManager(
new SpannedGridLayoutManager.GridSpanLookup() {
@OverRide
public SpannedGridLayoutManager.SpanInfo getSpanInfo(int position) {
if (position == 0) {
return new SpannedGridLayoutManager.SpanInfo(2, 1);
} else {
return new SpannedGridLayoutManager.SpanInfo(1, 1);
}
}
},
2/* Three columns /,
1f / We want our items to be 1:1 ratio */));
}
