### ISSUE TITLE
SpannedGridLayoutManager doesn't lay out rows below a contiguous blocks of "tall" cells

### ISSUE THREAD

**Issue by maxspencer** [android/plaid#218]
The simplest example of this problem is given by a `SpannedGridLayoutManager` with 1 column, 1.0 aspect ratio and all cells having dimensions 1 by 2. The recycler view will be initially be filled properly, but when scrolled down, no new cells/view will be laid out. Once all drawn views have scrolled off the top of the screen a `NullPointerException` is thrown.

The same problem can occur with multiple columns as long as there's a contiguous block of "tall" cells spanning all columns, see the below example with three columns:

![GIF showing problem](https://media.giphy.com/media/l0DAHY8yZCtdB8LPW/giphy.gif)

I have found a potential solution for this problem and will raise a PR soon.

**Comment by keyboardsurfer** [comment]
The SpannedGridLayoutManager is no longer in use in Plaid.
