### ISSUE TITLE
Possible fix for BottomSheet jumping when scrolling too fast

### ISSUE THREAD

**Issue by bernaferrari** [android/plaid#251]
After a lot of research on your BottomSheet, I found that this specific line is causing a glitch/jump when scrolling "too fast" or with too much strength and letting it go, as represented on the gif below: https://github.com/nickbutcher/plaid/blob/15fa49b24d75e3ae421ec9a6c5939988da5d5ae5/core/src/main/java/io/plaidapp/core/ui/widget/BottomSheet.java#L211
![ezgif-1-ccbf90692e](https://user-images.githubusercontent.com/351125/36362275-cb12702e-1511-11e8-8786-57f261a36002.gif)

Removing that line was enough for fixing it. I tested all the edge cases and nothing seems affected by it. Unless there is a very good reason for that line to be there, I would recommend removing it.

**Comment by keyboardsurfer** [comment]
Can't reproduce on current master.

**Comment by bernaferrari** [comment]
This is weird. I just checked and there was no change to Bottom Sheet since then. So the bug is probably still there.
