### ISSUE TITLE
SpannedGridLayoutManager loses all views if you scroll up too quickly on a long list

### ISSUE THREAD

**Issue by adityawasudeo** [android/plaid#254]
[Disclaimer: I'm not a professional Android dev and am entirely self taught, for weekend dabbling. Apologies if this isn't really an issue]

I'm using SpannedGridLayoutManager to implement a very long grid (1000+ items). I notice that scrolling fast to the top of the list from the 120 - 150th element causes the Layout to purge all child views and not redraw them. 

I dug into the code and found this in onLayoutChildren()

    int availableSpace = getHeight() - scrollOffset;
    ......
    while (availableSpace > 0 && lastVisiblePosition < lastItemPosition) {
            availableSpace -= layoutRow(row, startTop, recycler, state);
            row = getNextSpannedRow(row);
        }

scrollOffset is usually negative while scrolling up but becomes a very large positive number when it hits the top of the RecyclerView. availableSpace becomes a negative value and no rows get rendered.

I'm testing a fix for this condition

       if(availableSpace<0) availableSpace = getHeight();
        while (availableSpace > 0 && lastVisiblePosition < lastItemPosition) {

Appears to be working but I'll test more. Is there a more elegant fix I can deploy?

**Comment by dn0myaraymond** [comment]
I encountered your problem too. hope someone already fixed this issue

**Comment by keyboardsurfer** [comment]
Can't reproduce on master any longer.
