### ISSUE TITLE
[Bug] Strange background under Login view

### ISSUE THREAD

**Issue by XinyueZ** [android/plaid#444]
When close Login (press back) view we see a semi-transparent black background under the view. Is that the commitment of designer?

Device: Samsung S8
Android:  Android 7.x

<img width="499" alt="screen shot 2018-07-27 at 11 14 34" src="https://user-images.githubusercontent.com/7869833/43312811-9d604d78-918e-11e8-856f-0eddcce71899.png">

**Comment by florina-muntenescu** [comment]
Looks like an issue! 
We've marked this as "up for grabs" so feel free to create a fix for this. 
Thank you!

**Comment by apoorv9990** [comment]
I took a look at this. It seems the background is being derived from 
`<item name="android:windowBackground">@color/scrim</item>`
in `Plaid.Translucent` style .

Is the aim to provide a dialog like UI so that dar background goes away as soon as the login view is closed?

**Comment by nickbutcher** [comment]
Yes exactly.

**Comment by nickbutcher** [comment]
As per #676 I don't think that we should introduce the complexity of fixing this for a single device.
