### ISSUE TITLE
Shortcut has wrong icon for N_MR1(25)

### ISSUE THREAD

**Issue by JenyaKirmizaTripTop** [android/plaid#544]
on N_MR1  Instead of search icon we get some default android icon. I think it's because @drawable/ic_shortcut_search_foreground is only located on v26 folder. After you add this file to drawable/ it will be fixed

**Comment by JenyaKirmizaTripTop** [comment]
@tiembo thanks but i don't think that such small thing needs a pull request. maybe someone will include this next pr

**Comment by SubhanAli94** [comment]
@florina-muntenescu I fixed this issue by adding drawable but somehow I am unable to sign cla. I tried it many times but no luck. Any help regarding it will be much appreciated.

**Comment by pfmaggi** [comment]
Fixed in #710
