### ISSUE TITLE
NestedScrollView Issue

### ISSUE THREAD

**Issue by SezerFidanci** [android/plaid#598]
I am having the same problem

https://stackoverflow.com/questions/54167347/recycleview-scroll-issue-custom-layout-manager-with-nestedscrollview

**Comment by keyboardsurfer** [comment]
Is this an issue within Plaid? If so, please be more precise on what the issue is here.

**Comment by keyboardsurfer** [comment]
Closing this as stale. If it's an issue with Plaid please be more precise as to what happens within the app and how to reproduce it.
