### ISSUE TITLE
False positive tests

### ISSUE THREAD

**Issue by ataulm** [android/plaid#603]
I noticed a false positive when I was implementing the DN search.

https://github.com/nickbutcher/plaid/blob/master/core/src/test/java/io/plaidapp/core/designernews/domain/SearchStoriesUseCaseTest.kt#L91

The assert on this line can fail, but the test will pass because the exception is caught by something.

Here, I swapped `stories` for `null`:

```kotlin
@Test
fun search_withSuccess() = runBlocking {
    // Given a list of stories returned for a specific query and page
    val result = Result.Success(storiesResponses)
    whenever(storiesRepository.search(query, 1)).thenReturn(result)
    var sourceLoaded = false
    // Given a callback where we check the validity of the data received
    val callback = object : LoadSourceCallback {
        override fun sourceLoaded(result: List<PlaidItem>?, page: Int, source: String) {
            // Then the correct data is received
            sourceLoaded = true
            assertEquals(null, result)
            assertEquals(1, page)
            assertEquals(query, source)
        }
...
```

![image](https://user-images.githubusercontent.com/2678555/51443775-f2511780-1ce5-11e9-9855-d59b68e49e4c.png)

**Comment by arjunpola** [comment]
Created this #619 PR.

**Comment by arjunpola** [comment]
First time contributing. Please advice on how I can do better

**Comment by VMadalin** [comment]
The PR by @arjunpola related this issue is merged to _master_ on 11 Mar: https://github.com/android/plaid/pull/619. Maybe we should to close this opened issue
