### ISSUE TITLE
Animated GIFs not showing badge in grid

### ISSUE THREAD

**Issue by nickbutcher** [android/plaid#699]
![gif_badge](https://user-images.githubusercontent.com/352556/58246100-1da84980-7d4e-11e9-9cbb-f9534f8b2cba.gif)

**Comment by SubhanAli94** [comment]
By badge, you mean to say that comments icon and number in bottom-right corner?

**Comment by nickbutcher** [comment]
@SubhanAli94 no, animated images _should_ have a small indicator 'badge' saying "gif" on the bottom right (letting you know you can touch them to preview the animation as shown above). See https://github.com/android/plaid/pull/701

**Comment by SubhanAli94** [comment]
@nickbutcher Ok Thanks.
