### ISSUE TITLE
Not able to run instrumentation tests from Android Studio

### ISSUE THREAD

**Issue by vyshas** [android/plaid#708]
Android Studio: 3.4.
com.android.tools.build:gradle:3.4.0

Cannot run android tests from android studio, Edit Configuration window appears with "Error: The project cannot be run". 

Running tests from command line works

<img width="1370" alt="Screenshot 2019-05-26 at 20 42 45" src="https://user-images.githubusercontent.com/1193624/58386437-cb8a5100-7ff7-11e9-89b4-ec9f7122f7aa.png">

**Comment by scy1986320** [comment]
Could someone explain how do we run the instrumentation tests in dynamic feature module?

**Comment by wangchauyan** [comment]
I think it currently not able to run the instrument test via IDE itself. You can only run it via command line. check here: https://github.com/googlesamples/android-dynamic-features

```
Running instrumentation tests
In order to run instrumentation tests, parallel builds have to be turned off at the moment. This means you can run them via ./gradlew connectedAndroidTest --no-parallel.

Tooling support for this is being worked on – currently it's not possible to run instrumentation tests for dynamic-feature modules from Android Studio directly. Use the command line instead.
```

**Comment by keyboardsurfer** [comment]
Tracking here: https://issuetracker.google.com/145191501
