### ISSUE TITLE
Update CircleCI to API-29

### ISSUE THREAD

**Issue by nickbutcher** [android/plaid#731]
We need to upgrade circle for API 29 and new tools versions. Looks like this just [landed](https://github.com/circleci/circleci-images/pull/405) but still waiting for images to be built and [released](https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/android/images).

Once they are available we should upgrade to unblock Q dependent changes.

**Comment by AllanWang** [comment]
Fyi you have a duplicate issue (#672)

**Comment by nickbutcher** [comment]
Fixed in #790
