### ISSUE TITLE
Upgrade to OkHttp 4

### ISSUE THREAD

**Issue by nickbutcher** [android/plaid#741]
http://square.github.io/okhttp/upgrading_to_okhttp_4/

**Comment by CyborgRahil** [comment]
Raised a PR: https://github.com/android/plaid/pull/744 Please review your valuable feedback.

**Comment by Arpan-Patel** [comment]
Raised a PR #774 Please do review it.

**Comment by CyborgRahil** [comment]
@nickbutcher  Can you close this issue?
