### ISSUE TITLE
Transition issue with Android Q beta 5

### ISSUE THREAD

**Issue by Tolriq** [android/plaid#755]
Since it's already beta 5 and the issue will probably be stuck on level 1 external contractor filtering I'm posting this here too, sorry for that.

https://issuetracker.google.com/issues/137487202

Start Plaid, open anything with image to have a transition, press home, return to app via recent, press back, the normal transition does not run on Android Q beta 5 Pixel 3a and emulators.

Hoping this can reach the proper team faster with your help.

**Comment by Tolriq** [comment]
As supposed still present in beta 6 and a major user experience degradation.

Another simpler way to reproduce with Plaid, on beta 5/6 start plaid, open an item with an image to have the transition, press the image to open external browser, press back to quit external browser, press back the proper transition does not run.

For apps with multi levels transitions like show -> seasons -> episodes -> episode details, this totally ruins experience when going back.

**Comment by nickbutcher** [comment]
I cc'd the appropriate engineers but unfortunately it's likely to late to do anything for Q :-(

**Comment by Tolriq** [comment]
@nickbutcher Thanks I've seen :( I tried every way to bring attention to this quite important issue, kinda sad it still was not enough.

Some teams should learn from R8/D8 team, was a pleasure to work with them for nearly 1.5 year and have more than a dozen bugs fixed efficiently.

**Comment by Tolriq** [comment]
@nickbutcher so as expected it's still present in final, but can't comment on the issue anymore.

Do you know if I should open a new one or will it still be handled for 10.1 if that one happens?

**Comment by nickbutcher** [comment]
@Tolriq thanks for filing and following up on this. I got it moved to the right component on the issue tracker and assigned to the right team. Hope that it can get resolved, not sure when 🤷‍♀

**Comment by Tolriq** [comment]
Thanks a lot, usually I give up when I'm stuck at the 1st level external contractors, but the timing was awful :) Just finished passing dozens of hours polishing every transitions of the app to properly handle every edge cases, then discovering Q would break a large part was hard :p

**Comment by nickbutcher** [comment]
:'(

**Comment by Tolriq** [comment]
@nickbutcher Sorry to bother you but as expected the issue is still present in Android R preview 1 :(

Would be nice that such a basic and important thing for user experience do work correctly.

**Comment by nickbutcher** [comment]
😭 I've poked some internal bugs.

**Comment by Tolriq** [comment]
Thanks
