### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by IgorGanapolsky** [android/plaid#763]
Hello,
upon attempting to build your project in latest Android Studio Canary, there are build errors:
>google/plaid/core/build/generated/source/kapt/debug/io/plaidapp/core/util/glide/GlideOptions.java:50: error: cannot find symbol
  @CheckResult
   ^
  symbol:   class CheckResult
  location: class google/plaid/core/build/generated/source/kapt/debug/io/plaidapp/core/util/glide/GlideOptions.java:51: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class google/plaid/core/build/generated/source/kapt/debug/io/plaidapp/core/util/glide/GlideOptions.java:59: error: cannot find symbol
  @CheckResult

Please advise,
Igor

**Comment by emartynov** [comment]
Hey!

Is it still the case?
Can you try with the stable version of AS?
Is it part of gradle log or AS log that you shared?

Eugen

**Comment by tomislavhofman** [comment]
Project requires 3.6 or newer

```
* What went wrong:
This version of Android Studio cannot open this project, please retry with Android Studio 3.6 or newer.
```

**Comment by keyboardsurfer** [comment]
Can't reproduce with Studio 3.6. If the issue persists, please re-open with more context.
