### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by lulululbj** [android/plaid#773]
> This version of Android Studio cannot open this project, please retry with Android Studio 3.6 or newer.

My Android Studio version is 3.5.1

**Comment by BryceCui** [comment]
I want to update Android Studio 3.6 or higher. But the official website of 3.6 I can not download. Is there any solution? Or can you give me a download link?

**Comment by lulululbj** [comment]
> I want to update Android Studio 3.6 or higher. But the official website of 3.6 I can not download. Is there any solution? Or can you give me a download link?

https://dl.google.com/dl/android/studio/install/3.6.0.10/android-studio-ide-192.5842447-windows.exe?utm_source=androiddevtools&utm_medium=website

**Comment by BryceCui** [comment]
Is there a mac version, thank you

**Comment by lulululbj** [comment]
> Is there a mac version, thank you

降低项目 gradle 版本就可以了，不需要重下 AS

**Comment by BryceCui** [comment]
ok  谢谢

**Comment by kaiattrib** [comment]
修改 为 dependencies {
           classpath 'com.android.tools.build:gradle:3.3.1'}


和    distributionUrl=https\://services.gradle.org/distributions/gradle-5.1-all.zip  成功
