### ISSUE TITLE
Gradle Sync Issues

### ISSUE THREAD

**Issue by ekoo** [android/plaid#778]
ERROR: Plugin [id: 'com.diffplug.gradle.spotless', version: '3.14.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.diffplug.gradle.spotless:com.diffplug.gradle.spotless.gradle.plugin:3.14.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

**Comment by keyboardsurfer** [comment]
I can not reproduce this on current master. Please re-open if the issue persists.
