### ISSUE TITLE
PRs reviews and approvals speed

### ISSUE THREAD

**Issue by emartynov** [android/plaid#787]
Good evening owners and maintainers,

Would it be possible to speed up the review to the new PRs. That would significantly help with the closing/merging open contributions.

For example, the oldest opened PR was given review comment almost 3 months after opening. 

Would be adding CODEOWNERS file to this repository help? https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

**Comment by emartynov** [comment]
@florina-muntenescu thank you for picking up it. I will run over old issue and PRs to check if they are still relevant.

**Comment by keyboardsurfer** [comment]
Thanks for bringing this up. Yes we're picking up reviews and working our way through the backlog.
