### ISSUE TITLE
Facing Resources$NotFoundException when using large animated vector drawables

### ISSUE THREAD

**Issue by sanjeevirajm** [android/plaid#812]
You have disabled message in twitter, so using github issue tracker to reach you.
[NoRecordAnimation.zip](https://github.com/android/plaid/files/3985042/NoRecordAnimation.zip)
Facing Resources$NotFoundException when using large animated vector drawables. Can you check it?
@nickbutcher

**Comment by pfmaggi** [comment]
I'm closing this issue because this forum is for issues with Plaid.

[Stackoverflow](https://stackoverflow.com/questions/tagged/android-vectordrawable) might be a better forum for this kind of questions.
